from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('pricing/', views.pricing, name='pricing'),
    path('sales/', views.sales, name='sales'),
    path('stock/', views.stock, name='stock'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('resources/', views.resources, name='resources'),
    path('sales-analysis-data/', views.sales_analysis_data, name='sales_analysis_data'),
    path('sales-expense-profit-data/', views.sales_expense_profit_analysis, name='sales_expense_profit_analysis'),
    path('features/', views.features, name='features'),
    path('cashbook/', views.cashbook_page, name='cashbook'),
    path('debtor-ledger/', views.debtor_ledger_page, name='debtor_ledger'),
    path('api/cashbook/', views.cashbook_api, name='cashbook_api'),
    path('api/income-statement/', views.income_statement_api, name='income_statement_api'),
    path('api/product-details/', views.product_details_api, name='product_details_api'),
    path('api/debtor-credit/', views.debtor_credit_api, name='debtor_credit_api'),
    path('api/pay-debt/', views.pay_debt_api, name='pay_debt_api'),
    path('api/debtor-ledger/', views.debtor_ledger_api, name='debtor_ledger_api'),
    path('api/payment-history/', views.payment_history_api, name='payment_history_api'),
    path('api/overdue-debtors/', views.overdue_debtors_api, name='overdue_debtors_api'),
    path('api/search-suggestions/', views.search_suggestions_api, name='search_suggestions_api'),
    path('search/', views.global_search, name='search'),
    path('trading_report/', views.trading_report, name='trading_report'),
    path('credit_payment/', views.credit_payment, name='credit_payment'),
    path('register/', views.register, name='register'),
    path('verify-otp/', views.verify_otp, name='verify_otp'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]
