# Generated by Django 6.0 on 2026-03-03 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fix_stock_uniqueness_and_signal_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='main.commodity'),
        ),
    ]
