# Generated by Django 6.0 on 2026-03-04

import django.db.models.deletion
from django.db import migrations, models


def forwards_fill_tenant_relations(apps, schema_editor):
    Customer = apps.get_model("main", "Customer")
    Commodity = apps.get_model("main", "Commodity")
    Stock = apps.get_model("main", "Stock")
    Debtor = apps.get_model("main", "Debtor")
    db_alias = schema_editor.connection.alias

    first_customer = Customer.objects.using(db_alias).order_by("id").first()

    # Phase 1: put a customer on existing commodities when possible.
    for commodity in Commodity.objects.using(db_alias).filter(customer__isnull=True).order_by("id"):
        stock = Stock.objects.using(db_alias).filter(commodity_id=commodity.id).order_by("id").first()
        if stock:
            commodity.customer_id = stock.customer_id
        elif first_customer:
            commodity.customer_id = first_customer.id
        commodity.save(update_fields=["customer"])

    # Phase 2: split shared commodities per customer so each commodity is tenant-owned.
    for stock in Stock.objects.using(db_alias).all().order_by("id"):
        commodity = Commodity.objects.using(db_alias).get(id=stock.commodity_id)
        if commodity.customer_id == stock.customer_id:
            continue

        clone, _ = Commodity.objects.using(db_alias).get_or_create(
            customer_id=stock.customer_id,
            name=commodity.name,
            defaults={
                "buying_price": commodity.buying_price,
                "selling_price": commodity.selling_price,
                "number_of_commodity": commodity.number_of_commodity,
                "amount": commodity.amount,
                "total_amount": commodity.total_amount,
            },
        )
        stock.commodity_id = clone.id
        stock.name_commodity = clone.name
        stock.buying_price = clone.buying_price
        stock.amount = clone.amount
        stock.total_amount = clone.total_amount
        stock.save(update_fields=["commodity", "name_commodity", "buying_price", "amount", "total_amount"])

    # Phase 3: ensure debtor + default structures exist for every customer.
    for customer in Customer.objects.using(db_alias).all().order_by("id"):
        Debtor.objects.using(db_alias).get_or_create(
            customer_id=customer.id,
            defaults={
                "current_balance": 0,
                "credit_limit": 0,
            },
        )

        default_commodity, _ = Commodity.objects.using(db_alias).get_or_create(
            customer_id=customer.id,
            name="Default Commodity",
            defaults={
                "buying_price": 0,
                "selling_price": 0,
                "number_of_commodity": 0,
                "amount": 0,
                "total_amount": 0,
            },
        )
        Stock.objects.using(db_alias).get_or_create(
            customer_id=customer.id,
            commodity_id=default_commodity.id,
            defaults={
                "name_commodity": default_commodity.name,
                "number_of_commodity": default_commodity.number_of_commodity,
                "buying_price": default_commodity.buying_price,
                "amount": default_commodity.amount,
                "total_amount": default_commodity.total_amount,
            },
        )

        for commodity in Commodity.objects.using(db_alias).filter(customer_id=customer.id):
            Stock.objects.using(db_alias).get_or_create(
                customer_id=customer.id,
                commodity_id=commodity.id,
                defaults={
                    "name_commodity": commodity.name,
                    "number_of_commodity": commodity.number_of_commodity,
                    "buying_price": commodity.buying_price,
                    "amount": commodity.amount,
                    "total_amount": commodity.total_amount,
                },
            )


def backwards_noop(apps, schema_editor):
    # No destructive reverse data migration to avoid dropping tenant data.
    return


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_stock_commodity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Debtor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("current_balance", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("credit_limit", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debtor",
                        to="main.customer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="commodity",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commodities",
                to="main.customer",
            ),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.RunPython(forwards_fill_tenant_relations, backwards_noop),
        migrations.AddConstraint(
            model_name="commodity",
            constraint=models.UniqueConstraint(
                fields=("customer", "name"),
                name="unique_commodity_per_customer_name",
            ),
        ),
    ]
