# Generated by Django 6.0 on 2026-03-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tenant_model_bootstrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='buyer_name',
            field=models.CharField(default='Unknown Buyer', max_length=200),
        ),
    ]
