# Generated by Django 6.0 on 2026-03-06 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sales_payment_type_and_debtors_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='main.commodity'),
        ),
    ]
