# Generated by Django 6.0 on 2026-03-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_sales_commodity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='expected_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='expected_selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='expected_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
