# Generated by Django 6.0 on 2026-03-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_stock_expected_sales_stock_expected_selling_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='expected_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
