# Generated by Django 6.0 on 2026-03-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_commodity_expected_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='expected_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
