# Generated by Django 6.0 on 2026-03-29 07:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_customer_email_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtors',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debtors',
            name='is_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debtors',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='DebtorLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='main.debtors')),
            ],
            options={
                'ordering': ['date', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('debit__gte', 0)), name='debtor_ledger_debit_gte_0'), models.CheckConstraint(condition=models.Q(('credit__gte', 0)), name='debtor_ledger_credit_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], default='cash', max_length=10)),
                ('reference', models.CharField(blank=True, default='', max_length=200)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.debtors')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_paid__gt', 0)), name='payment_amount_gt_0')],
            },
        ),
    ]
